require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GooglePlusDataController do

  # This should return the minimal set of attributes required to create a valid
  # GooglePlusDatum. As you add validations to GooglePlusDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GooglePlusDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all google_plus_data as @google_plus_data" do
      google_plus_datum = GooglePlusDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:google_plus_data).should eq([google_plus_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested google_plus_datum as @google_plus_datum" do
      google_plus_datum = GooglePlusDatum.create! valid_attributes
      get :show, {:id => google_plus_datum.to_param}, valid_session
      assigns(:google_plus_datum).should eq(google_plus_datum)
    end
  end

  describe "GET new" do
    it "assigns a new google_plus_datum as @google_plus_datum" do
      get :new, {}, valid_session
      assigns(:google_plus_datum).should be_a_new(GooglePlusDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested google_plus_datum as @google_plus_datum" do
      google_plus_datum = GooglePlusDatum.create! valid_attributes
      get :edit, {:id => google_plus_datum.to_param}, valid_session
      assigns(:google_plus_datum).should eq(google_plus_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GooglePlusDatum" do
        expect {
          post :create, {:google_plus_datum => valid_attributes}, valid_session
        }.to change(GooglePlusDatum, :count).by(1)
      end

      it "assigns a newly created google_plus_datum as @google_plus_datum" do
        post :create, {:google_plus_datum => valid_attributes}, valid_session
        assigns(:google_plus_datum).should be_a(GooglePlusDatum)
        assigns(:google_plus_datum).should be_persisted
      end

      it "redirects to the created google_plus_datum" do
        post :create, {:google_plus_datum => valid_attributes}, valid_session
        response.should redirect_to(GooglePlusDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved google_plus_datum as @google_plus_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        GooglePlusDatum.any_instance.stub(:save).and_return(false)
        post :create, {:google_plus_datum => {}}, valid_session
        assigns(:google_plus_datum).should be_a_new(GooglePlusDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GooglePlusDatum.any_instance.stub(:save).and_return(false)
        post :create, {:google_plus_datum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested google_plus_datum" do
        google_plus_datum = GooglePlusDatum.create! valid_attributes
        # Assuming there are no other google_plus_data in the database, this
        # specifies that the GooglePlusDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GooglePlusDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => google_plus_datum.to_param, :google_plus_datum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested google_plus_datum as @google_plus_datum" do
        google_plus_datum = GooglePlusDatum.create! valid_attributes
        put :update, {:id => google_plus_datum.to_param, :google_plus_datum => valid_attributes}, valid_session
        assigns(:google_plus_datum).should eq(google_plus_datum)
      end

      it "redirects to the google_plus_datum" do
        google_plus_datum = GooglePlusDatum.create! valid_attributes
        put :update, {:id => google_plus_datum.to_param, :google_plus_datum => valid_attributes}, valid_session
        response.should redirect_to(google_plus_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the google_plus_datum as @google_plus_datum" do
        google_plus_datum = GooglePlusDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GooglePlusDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => google_plus_datum.to_param, :google_plus_datum => {}}, valid_session
        assigns(:google_plus_datum).should eq(google_plus_datum)
      end

      it "re-renders the 'edit' template" do
        google_plus_datum = GooglePlusDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GooglePlusDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => google_plus_datum.to_param, :google_plus_datum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested google_plus_datum" do
      google_plus_datum = GooglePlusDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => google_plus_datum.to_param}, valid_session
      }.to change(GooglePlusDatum, :count).by(-1)
    end

    it "redirects to the google_plus_data list" do
      google_plus_datum = GooglePlusDatum.create! valid_attributes
      delete :destroy, {:id => google_plus_datum.to_param}, valid_session
      response.should redirect_to(google_plus_data_url)
    end
  end

end
