require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YoutubeDataController do

  # This should return the minimal set of attributes required to create a valid
  # YoutubeDatum. As you add validations to YoutubeDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YoutubeDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all youtube_data as @youtube_data" do
      youtube_datum = YoutubeDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:youtube_data).should eq([youtube_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested youtube_datum as @youtube_datum" do
      youtube_datum = YoutubeDatum.create! valid_attributes
      get :show, {:id => youtube_datum.to_param}, valid_session
      assigns(:youtube_datum).should eq(youtube_datum)
    end
  end

  describe "GET new" do
    it "assigns a new youtube_datum as @youtube_datum" do
      get :new, {}, valid_session
      assigns(:youtube_datum).should be_a_new(YoutubeDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested youtube_datum as @youtube_datum" do
      youtube_datum = YoutubeDatum.create! valid_attributes
      get :edit, {:id => youtube_datum.to_param}, valid_session
      assigns(:youtube_datum).should eq(youtube_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new YoutubeDatum" do
        expect {
          post :create, {:youtube_datum => valid_attributes}, valid_session
        }.to change(YoutubeDatum, :count).by(1)
      end

      it "assigns a newly created youtube_datum as @youtube_datum" do
        post :create, {:youtube_datum => valid_attributes}, valid_session
        assigns(:youtube_datum).should be_a(YoutubeDatum)
        assigns(:youtube_datum).should be_persisted
      end

      it "redirects to the created youtube_datum" do
        post :create, {:youtube_datum => valid_attributes}, valid_session
        response.should redirect_to(YoutubeDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved youtube_datum as @youtube_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeDatum.any_instance.stub(:save).and_return(false)
        post :create, {:youtube_datum => {}}, valid_session
        assigns(:youtube_datum).should be_a_new(YoutubeDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeDatum.any_instance.stub(:save).and_return(false)
        post :create, {:youtube_datum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested youtube_datum" do
        youtube_datum = YoutubeDatum.create! valid_attributes
        # Assuming there are no other youtube_data in the database, this
        # specifies that the YoutubeDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        YoutubeDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => youtube_datum.to_param, :youtube_datum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested youtube_datum as @youtube_datum" do
        youtube_datum = YoutubeDatum.create! valid_attributes
        put :update, {:id => youtube_datum.to_param, :youtube_datum => valid_attributes}, valid_session
        assigns(:youtube_datum).should eq(youtube_datum)
      end

      it "redirects to the youtube_datum" do
        youtube_datum = YoutubeDatum.create! valid_attributes
        put :update, {:id => youtube_datum.to_param, :youtube_datum => valid_attributes}, valid_session
        response.should redirect_to(youtube_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the youtube_datum as @youtube_datum" do
        youtube_datum = YoutubeDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => youtube_datum.to_param, :youtube_datum => {}}, valid_session
        assigns(:youtube_datum).should eq(youtube_datum)
      end

      it "re-renders the 'edit' template" do
        youtube_datum = YoutubeDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => youtube_datum.to_param, :youtube_datum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested youtube_datum" do
      youtube_datum = YoutubeDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => youtube_datum.to_param}, valid_session
      }.to change(YoutubeDatum, :count).by(-1)
    end

    it "redirects to the youtube_data list" do
      youtube_datum = YoutubeDatum.create! valid_attributes
      delete :destroy, {:id => youtube_datum.to_param}, valid_session
      response.should redirect_to(youtube_data_url)
    end
  end

end
